### Muhammad Sikandar Hussain
### 502808


#6.	Reshaping arrays with NumPy:
#Create a function that takes a NumPy array of shape (length,width,height) and converts it in to a vector of shape (length*width*height,1). Use the function array.reshape() for this.
import numpy as np

**Explanation:** Reshaping changes only the arrangement of the values, not the values themselves. A 3-D array with dimensions `length × width × height` contains `length * width * height` elements, so `reshape(..., 1)` converts it into a single-column vector.

In [1]:
 

def reshape_array(input_array):
    length , width, height = input_array.shape
    return input_array.reshape(length * width * height, 1)

# example 
input_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # shape (2, 2, 2)

result = reshape_array(input_array)
print("Original array shape : ", input_array.shape)
print("Reshaped array shape : ", result.shape)
print(result)  


Original array shape :  (2, 2, 2)
Reshaped array shape :  (8, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


7.	Building a basic mathematical function with NumPy:
a)	Write a function that returns the sigmoid of a real number x. Use math.exp(x) for the exponential function. Sigmoid(x)=1/(1+exp(-x)).

**Explanation:** The sigmoid function maps any real number to a value between 0 and 1. Here, `math.exp()` calculates the exponential for one scalar input, and the example shows the sigmoid value for `x = 0.5`.

In [2]:
import math

def sigmoid(x):
    return 1/(1 + math.exp(-x))

# example
x = 0.5
result = sigmoid(x)

print("Sigmoid of", x, "is", result)

Sigmoid of 0.5 is 0.6224593312018546


b)	Now create a list of 5 values and call your sigmoid function with the list as input. You will get an error because math.exp() only works when input is a real number. It does not work with vectors and matrices.

**Explanation:** This task intentionally produces a `TypeError`. A Python list cannot be negated element by element, and `math.exp()` accepts only one number at a time, showing why this scalar implementation cannot process a vector directly.

In [4]:
def sigmoid(x):
    return 1/(1 + math.exp(-x))
values = [1, 2, 3, 4, 5]

print(sigmoid(values))

TypeError: bad operand type for unary -: 'list'

c) Now create a new function for sigmoid but this time use np.exp() instead of math.exp(). Np.exp() works with all types of inputs including real numbers, vectors and matrices. In deep learning we mostly use matrices and vectors. This is why NumPy is more useful. Call your new function with a vector created by np.array() function.

**Explanation:** `np.exp()` performs the calculation element by element, so the same sigmoid formula is applied to every value in the NumPy array at once. This vectorized approach is convenient and efficient for machine-learning data.

In [8]:
import numpy as np

def sigmoid_np(x):
    return 1 / (1 + np.exp(-x))

# Create a vector
values = np.array([1, 2, 3, 4, 5])

result = sigmoid_np(values)

print("Input:", values)
print("Sigmoid:", result)

Input: [1 2 3 4 5]
Sigmoid: [0.73105858 0.88079708 0.95257413 0.98201379 0.99330715]


Implementing a function on a matrix:
Create a function that takes a matrix as input and returns the softmax (by row) of matrix. The softmax function is defined like this:

softmax(x)=softmax([x_1  x_2… x_n ])=[e^(x_1 )/(∑_j▒e^(x_j ) )    e^(x_2 )/(∑_j▒e^(x_j ) )  …   e^(x_n )/(∑_j▒e^(x_j ) )]

Check if your function is working correctly by using suitable inputs.

**Explanation:** Softmax converts each row into a probability distribution. Every value becomes positive after exponentiation, and division by the row sum makes the values in each row add up to 1; larger inputs receive larger probabilities.


In [11]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

#test the softmax function
matrix = np.array([[1, 2, 3],
                [4, 5, 6]])

result = softmax(matrix)

print("Input matrix:\n", matrix)
print("Softmax result:\n", result)

Input matrix:
 [[1 2 3]
 [4 5 6]]
Softmax result:
 [[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]


9.	Finding dot product using NumPy:

a.	Create a function that implements dot product of two vectors. The input to the function should be two standard python lists. Identify the time taken to evaluate the dot product using a particular example of your choice.

**Explanation:** The dot product multiplies corresponding elements and adds the products to produce one scalar. This version uses a Python loop, while the timer records how long the calculation takes.


In [15]:
import time
def dot_product_of_matrices(A, B):
    result = 0

    for i in range(len(A)):
        result += A[i] * B[i]

    return result

#example vectors
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]

# Measure execution time
start_time = time.time()

result = dot_product_of_matrices(a, b)

end_time = time.time()

print("Dot Product:", result)
print("Time taken:", end_time - start_time, "seconds")

Dot Product: 130
Time taken: 0.00013113021850585938 seconds


b.	Now create another function that implements dot product of two vectors using np.dot() function. Identify the time taken to evaluate this dot product and compare it with the time taken in part a.

**Explanation:** `np.dot()` performs the same dot-product operation using optimized NumPy code. For large vectors it is generally faster than an explicit Python loop, although timings for very small inputs may be too short to compare reliably.

In [16]:
import numpy as np
import time 

def dot_product_of_matrices_np(A, B):
    return np.dot(A, B)

#example vectors
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

# Measure execution time
start_time = time.time()
result = dot_product_of_matrices_np(a, b)
end_time = time.time()  

print("Dot Product:", result)
print("Time taken:", end_time - start_time, "seconds")

Dot Product: 130
Time taken: 0.00020503997802734375 seconds


Compare execution time

For a better comparison, use larger vectors:

**Explanation:** Larger vectors make the performance difference easier to observe. Both methods should return the same mathematical result, but NumPy usually completes the repeated arithmetic more efficiently.

In [18]:
import numpy as np
import time

# Large vectors
a = list(range(100000))
b = list(range(100000))

# Python implementation
start = time.time()
result_python = dot_product_of_matrices(a, b)
python_time = time.time() - start

# NumPy implementation
a_np = np.array(a)
b_np = np.array(b)

start = time.time()
result_numpy = np.dot(a_np, b_np)
numpy_time = time.time() - start

print("Python Dot Product:", result_python)
print("Python Time:", python_time, "seconds")

print("\nNumPy Dot Product:", result_numpy)
print("NumPy Time:", numpy_time, "seconds")

Python Dot Product: 333328333350000
Python Time: 0.027799129486083984 seconds

NumPy Dot Product: 333328333350000
NumPy Time: 0.00046753883361816406 seconds


10.	Finding outer product using NumPy:

a)	Create a function that implements outer product of two vectors. The input to the function should be two standard python lists. Identify the time taken to evaluate the outer product using a particular example of your choice.

**Explanation:** The outer product multiplies every element of the first vector by every element of the second vector. The result is a matrix with `len(a)` rows and `len(b)` columns.


In [19]:
import time

def outer_product_of_matrices(a, b):
    result = []

    for i in range(len(a)):
        row = []
        for j in range(len(b)):
            row.append(a[i] * b[j])
        result.append(row)

    return result

# example vectors
a = [1, 2, 3]
b = [4, 5]

start_time = time.time()
result = outer_product_of_matrices(a, b)
end_time = time.time()  

print("Outer Product:", result)
print("Time taken:", end_time - start_time, "seconds")

Outer Product: [[4, 5], [8, 10], [12, 15]]
Time taken: 0.00011754035949707031 seconds


b)	Now create another function that implements outer product of two vectors using np.outer() function. Identify the time taken to evaluate this dot product and compare it with the time taken in part a.

**Explanation:** `np.outer()` builds the complete outer-product matrix without manually written nested loops. It is shorter and normally faster for large vectors because NumPy performs the operation in optimized compiled code.

In [20]:
import numpy as np
import time

def outer_product_of_matrices_np(A, B):
    return np.outer(a , b)

#example vectors
a = np.array([1, 2, 3])
b = np.array([4, 5])

start_time = time.time()
result = outer_product_of_matrices_np(a, b)
end_time = time.time()

print("Outer Product:", result)
print("Time taken:", end_time - start_time, "seconds")

Outer Product: [[ 4  5]
 [ 8 10]
 [12 15]]
Time taken: 0.0005521774291992188 seconds


Compare execution time

For a better comparison, use larger vectors:

**Explanation:** Using 1,000-element vectors creates a 1,000 × 1,000 result, making the cost of the Python nested loops visible. The comparison demonstrates the benefit of NumPy vectorization.

In [21]:
import numpy as np
import time

a = list(range(1000))
b = list(range(1000))

# Python implementation
start = time.time()
result_python = outer_product_of_matrices(a, b)
python_time = time.time() - start

# NumPy implementation
a_np = np.array(a)
b_np = np.array(b)

start = time.time()
result_numpy = np.outer(a_np, b_np)
numpy_time = time.time() - start

print("Python Time:", python_time, "seconds")
print("NumPy Time:", numpy_time, "seconds")

Python Time: 0.13512134552001953 seconds
NumPy Time: 0.006640911102294922 seconds


## Task 11 — L1 and L2 Loss Functions

**Explanation:** Loss functions measure the difference between true and predicted values. L1 loss sums absolute errors, while L2 loss sums squared errors and therefore penalizes large errors more strongly.

### 11(a) L1 Loss using Python lists

**Explanation:** A loop calculates the absolute difference for each true/predicted pair and adds the differences. This produces the total L1 loss using standard Python only.


In [22]:
def l1_regularization_python(y_true, y_pred):
    loss = 0

    for i in range(len(y_true)):
        loss += abs(y_true[i] - y_pred[i])

    return loss

# example
y_true = [1, 2, 3, 4]
y_pred = [2, 3, 4, 5]
loss = l1_regularization_python(y_true, y_pred)
print("L1 Regularization Loss:", loss)

L1 Regularization Loss: 4


### 11(b) L1 Loss using NumPy

**Explanation:** NumPy subtracts the arrays element by element, `np.abs()` removes the signs, and `np.sum()` combines all errors into one L1 loss value.

In [25]:
import numpy as np
def l1_regularization_numpy(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    loss = np.sum(np.abs(y_true - y_pred))
    return loss

# example
y_true = [1, 2, 3, 4]
y_pred = [2, 3, 4, 5]
loss = l1_regularization_numpy(y_true, y_pred)  
print("L1 Regularization Loss:", loss)


L1 Regularization Loss: 4


### 11(c) L2 Loss using Python lists

**Explanation:** This loop squares each prediction error before adding it to the total. Squaring prevents negative and positive errors from cancelling and gives extra weight to larger errors.

In [26]:
def l2_regularization_python(y_true, y_pred):
    loss = 0

    for i in range(len(y_true)):
        loss += (y_true[i] - y_pred[i]) ** 2

    return loss
 #example
y_true = [1, 2, 3, 4]
y_pred = [2, 3, 4, 5]       

loss = l2_regularization_python(y_true, y_pred)
print("L2 Regularization Loss:", loss)

L2 Regularization Loss: 4


### 11(d) L2 Loss using NumPy

**Explanation:** NumPy computes all element-wise errors together, squares them, and sums them. This is the vectorized equivalent of the Python-loop L2 calculation.

In [27]:
def l2_regularization_numpy(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    loss = np.sum((y_true - y_pred) ** 2)
    return loss

# example
y_true = [1, 2, 3, 4]
y_pred = [2, 3, 4, 5]   

loss = l2_regularization_numpy(y_true, y_pred)  
print("L2 Regularization Loss:", loss)

L2 Regularization Loss: 4


## Task 12 — Matrix Addition

**Explanation:** Matrix addition combines two matrices of the same shape by adding corresponding entries. The output matrix therefore has the same number of rows and columns as both inputs.

### 12(a) Using standard Python

**Explanation:** Nested loops visit each row and column, add the matching values from matrices `a` and `b`, and store each sum in a new matrix.

In [28]:
def matrix_addition_python(a,b):
    row = len(a)
    cols = len(a[0])

    result = []

    for i in range(row):
        row = []
        for j in range(cols):
            row.append(a[i][j] + b[i][j])
        result.append(row)
    return result

# example matrices 
a = [[1, 2, 3], [4, 5, 6]]
b = [[7, 8, 9], [10, 11, 12]]

result = matrix_addition_python(a, b)
print("Matrix Addition Result:")
for row in result:
    print(row)

Matrix Addition Result:
[8, 10, 12]
[14, 16, 18]


### 12(b) Using NumPy

**Explanation:** Adding two NumPy arrays with `+` performs element-wise matrix addition directly. It gives the same result as the nested-loop version with much less code.

In [29]:
import numpy as np

def matrix_add_numpy(a,b):
    return np.array(a) + np.array(b)


A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

result = matrix_add_numpy(A, B)

print("A + B:")
print(result)

A + B:
[[ 8 10 12]
 [14 16 18]]


## Task 13 — Matrix and Vector Multiplication

**Explanation:** Matrix-vector multiplication takes the dot product of every matrix row with the vector. A matrix with `m` rows produces an output vector containing `m` values.

### 13(a) Using standard Python

**Explanation:** For each matrix row, the inner loop multiplies its entries by the matching vector entries and sums them. Each total becomes one element of the result vector.

In [30]:
def matrix_vector_multiply_python(A, v):
    result = []

    for i in range(len(A)):
        total = 0

        for j in range(len(v)):
            total += A[i][j] * v[j]

        result.append(total)

    return result


# Example matrix
A = [
    [1, 2, 3],
    [4, 5, 6]
]

# Example vector
v = [7, 8, 9]

result = matrix_vector_multiply_python(A, v)

print("Matrix:")
print(A)

print("\nVector:")
print(v)

print("\nMatrix × Vector:")
print(result)

Matrix:
[[1, 2, 3], [4, 5, 6]]

Vector:
[7, 8, 9]

Matrix × Vector:
[50, 122]


### 13(b) Using NumPy

**Explanation:** `np.dot(A, v)` performs all row-vector dot products in one call. The matrix column count must match the number of elements in the vector.

In [31]:
import numpy as np

def matrix_vector_multiply_numpy(A, v):
    return np.dot(A, v)


A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

v = np.array([7, 8, 9])

result = matrix_vector_multiply_numpy(A, v)

print("Matrix:")
print(A)

print("\nVector:")
print(v)

print("\nMatrix × Vector:")
print(result)

Matrix:
[[1 2 3]
 [4 5 6]]

Vector:
[7 8 9]

Matrix × Vector:
[ 50 122]


## Task 14 — Matrix Multiplication

**Explanation:** Matrix multiplication calculates each output entry as the dot product of a row from the first matrix and a column from the second. The first matrix's column count must equal the second matrix's row count.

### 14(a) Using standard Python

**Explanation:** Three nested loops select an output row, an output column, and then accumulate the products needed for that position. This shows the individual steps behind matrix multiplication.

In [32]:
def matrix_multiply_python(A, B):
    rows_A = len(A)
    cols_A = len(A[0])
    cols_B = len(B[0])

    result = []

    for i in range(rows_A):
        row = []

        for j in range(cols_B):
            total = 0

            for k in range(cols_A):
                total += A[i][k] * B[k][j]

            row.append(total)

        result.append(row)

    return result


# Example matrices
A = [
    [1, 2],
    [3, 4]
]

B = [
    [5, 6],
    [7, 8]
]

result = matrix_multiply_python(A, B)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nA × B:")
print(result)

Matrix A:
[[1, 2], [3, 4]]

Matrix B:
[[5, 6], [7, 8]]

A × B:
[[19, 22], [43, 50]]


### 14(b) Using NumPy

**Explanation:** `np.dot(A, B)` carries out matrix multiplication in a concise, optimized operation. The resulting matrix matches the one produced by the manual triple-loop implementation.

In [33]:
import numpy as np

def matrix_multiply_numpy(A, B):
    return np.dot(A, B)


A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = matrix_multiply_numpy(A, B)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nA × B:")
print(result)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A × B:
[[19 22]
 [43 50]]
